services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live_sports_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      DB_SSL: "false"
    ports:
      - "3000:3000"

